#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
from titanictraining import TitanicTraining

# Get the current file's directory
current_dir = os.path.dirname(os.path.realpath(__file__))
print(current_dir)

# Set the home directory to the root folder
HOME_DIR = os.path.abspath(os.path.join(current_dir, "../../../"))

# Use the home directory as needed
print("Home directory:", HOME_DIR)

# Get the data directory path
data_dir = os.path.join(HOME_DIR, "src/data")
print("Data directory:", data_dir)

train_data = os.path.join(data_dir, "train.csv")
test_data = os.path.join(data_dir, "test.csv")
test_result = os.path.join(data_dir, "gender_submission.csv")


titanic = TitanicTraining(train_data, test_data, test_result)
print(titanic.run())
